<a href="https://colab.research.google.com/github/veritaem/DS-Unit-2-Sprint-2-Linear-Regression/blob/master/Copy_of_Gradient_Descent_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Gradient Descent Implementation Challenge!!

## Use gradient descent to find the optimal parameters of a **multiple** regression model. (We only showed an implementation for a bivariate model during lecture.)

A note: Implementing gradient descent in any context is not trivial, particularly the step where we calculate the gradient will change based on the number of parameters that we're trying to optimize for. You will need to research what the gradient of a multiple regression model looks like. This challenge is pretty open-ended but I hope it will be thrilling. Please work together, help each other, share resources and generally expand your understanding of gradient descent as you try and achieve this implementation. 

## Suggestions:

Start off with a model that has just two $X$ variables You can use any datasets that have at least two x variables. Potential candidates might be the blood pressure dataset that we used during lecture on Monday: [HERE](https://college.cengage.com/mathematics/brase/understandable_statistics/7e/students/datasets/mlr/excel/mlr02.xls) or any of the housing datasets. You would just need to select from them the two varaibles $x$ variables and one y variable that you want to work with that you most want to work with. 

Use Sklearn to find the optimal parameters of your model first. (like we did during the lecture.) So that you can compare the parameter estimates of your gradient-descent linear regression to the estimates of OLS linear regression. If implemented correctly they should be nearly identical.

Becoming a Data Scientist is all about striking out into the unknown, getting stuck and then researching and fighting and learning until you get yourself unstuck. Work together! And fight to take your own learning-rate fueled step towards your own optimal understanding of gradient descent! 


In [2]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving mlr02.xls to mlr02.xls
User uploaded file "mlr02.xls" with length 751 bytes


In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from mpl_toolkits.mplot3d import Axes3D

In [22]:
data = 'mlr02.xls'
df = pd.read_excel(data)

*** No CODEPAGE record, no encoding_override: will use 'ascii'


In [65]:
df = df.rename(index = str, columns = {'age':'weight', 'bp':'age', 'weight':'bp'})
df.head()

weight  age   bp
0     132   52  173
1     143   59  184
2     153   67  194
3     162   73  211
4     154   64  196

In [0]:
y = df.bp.values
X = df.iloc[:, :-1].values
#seaparating them into a target and the features to determine the target

In [75]:
y = pd.DataFrame(y)
y

0
0   173
1   184
2   194
3   211
4   196
5   220
6   188
7   188
8   207
9   167
10  217

In [76]:
X = np.mat(X)
X

matrix([[132,  52],
        [143,  59],
        [153,  67],
        [162,  73],
        [154,  64],
        [168,  74],
        [137,  54],
        [149,  61],
        [159,  65],
        [128,  46],
        [166,  72]])

In [77]:
X = (X - X.mean()) / X.std()
X

matrix([[ 0.56930473, -1.20097146],
        [ 0.8127177 , -1.04607229],
        [ 1.03400223, -0.86904467],
        [ 1.2331583 , -0.73627396],
        [ 1.05613068, -0.93543003],
        [ 1.36592901, -0.71414551],
        [ 0.67994699, -1.15671455],
        [ 0.94548842, -1.00181539],
        [ 1.16677294, -0.91330158],
        [ 0.48079092, -1.33374217],
        [ 1.32167211, -0.75840241]])

In [78]:
model = LinearRegression()
model.fit(X, y)
beta_1 = model.coef_[0]
beta_0 = model.intercept_
print(beta_1)
print(beta_0)
#getting the y intercept especially so my SSe will hopefully be less

[60.8405366  -7.80609914]
[128.43826237]


#Way 1 
###(trying to understand what gradient descent is a little more)

$Blood Pressure =W_0weight + W_1age$

In [0]:
def prediction(weights, features):
  return np.dot(weights, features)

In [0]:
W1 = 0
W2 = 0
weights = np.array([[W1],
                    [W2]])

In [0]:
def c_func(features, target, weights):
  Target = len(target)
  prediction = predict(weights, features)
  SE = (prediction - targets)**2
  return 1.0/(2*Target) * SE.sum()

In [0]:
def move_weights(features, target, weights, alpha):
  predicto = prediction(features, weights)
  f1 = features[:,0]
  f2 = features[:,1]
  der_f1 = -f1*(target - predicto)
  der_f2 = -f2*(target - predicto)
  weights[0][0] -= (alpha * np.mean(der_f1))
  weights[1][0] -= (alpha * np.mean(der_f2))
  return weights

#Way 2
##(from class sort of)

In [0]:
# Initial Variables
alpha = .01
iterations = 2500
n = len(y)
np.random.seed(7337)
theta = [0, 0]

In [85]:
predictis = np.dot(X, theta)
print(predictis)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [91]:
error = predictis - y.T
print(error)

[[-173. -184. -194. -211. -196. -220. -188. -188. -207. -167. -217.]]


In [97]:
theta = theta - (alpha * (1/n) * np.dot(X.T, error.T))
print(theta)

[[ 3.87368616  3.87368616]
 [-3.72148264 -3.72148264]]


In [110]:
def gradient_descent(X, y, theta, iterations, alpha):
  for _ in range(iterations):
    prediction = np.dot(X, theta)
    error = prediction - y
    updates = (alpha * (1/n) * np.dot(X.T, error))
    theta = theta - updates
  return theta
  
past_thetas, past_costs = gradient_descent(X, y, theta, iterations, alpha)
final_theta = past_thetas[-1]
final_theta.T[0], final_theta.T[1]

(matrix([[113.07579614]]), matrix([[113.07579614]]))

# Stretch Goals

If you happen upon the most useful resources for accomplishing this challenge first, I want you to spend time today studying other variations of Gradient Descent-Based Optimizers.

- Try and write a function that can perform gradient descent for arbitarily large (in dimensionality) multiple regression models. 
- Create a notebook for yourself exploring these topics
- How do they differ from the "vanilla" gradient descent we explored today
- How do these different gradient descent-based optimizers seek to overcome the challenge of finding the global minimum among various local minima?
- Write a blog post that reteaches what you have learned about these other gradient descent-based optimizers.

[Overview of GD-based optimizers](http://ruder.io/optimizing-gradient-descent/)

[Siraj Raval - Evolution of Gradient Descent-Based Optimizers](https://youtu.be/nhqo0u1a6fw)